# Generated by Django 3.1.5 on 2021-01-30 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('routine_name', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('weekday', models.CharField(blank=True, default='Mon', max_length=40)),
                ('done', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('repetition', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('routine_id', models.ForeignKey(db_column='routine_id', on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='health.routine')),
            ],
        ),
    ]
