# Generated by Django 3.1.5 on 2021-01-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20210130_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='owner',
        ),
        migrations.AddField(
            model_name='routine',
            name='routine_user',
            field=models.CharField(default='no users', max_length=30),
        ),
    ]
