# Generated by Django 3.1.5 on 2021-01-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20210130_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='routine_name',
            field=models.CharField(max_length=30),
        ),
    ]
