# Generated by Django 3.1.5 on 2021-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20210131_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='repetition',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
