# Generated by Django 3.1.5 on 2021-01-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20210131_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='repetition',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
